version: 1
jobs:
  build:
    working_directory: dkhamsing/open-source-ios-app
    parallelism: 
    shell: /bin/bash 
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    docker:
    - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
    steps:
    - checkout
    - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
    - run:
        working_directory: ~/dkhamsing/open-source-ios-apps
        command:  dkhamsing/open-source-ios-apps/.rvmrc; echo 2.4.0 > dkhamsing/open-source-ios-apps/.ruby-version; rvm use 2.4.0 --default
    - restore_cache:
        keys:
        - v1-dep-
        - v1-dep-master-
        - v1-dep-
    - save_cache:
        key: 
        paths:
        - vendor/bundle
        - ~/virtualenvs
        - ~/.m2
        - ~/.ivy2
        - ~/.bundle
        - ~/.go_workspace
        - ~/.gradle
        - ~/.cache/bower
    - run: sudo pip install json-spec
    - run: json validate =.github/schema.json --document-file=contents.json
    - run: github/osia_validate_categories.rb
    - store_test_results:
        path: /tmp/circleci-test-results
      Save artifacts
    - store_artifacts:
        path: /tmp/circleci-artifacts
    - store_artifacts:
        path: /tmp/circleci-test-results
  deploy:
    working_directory: ~/dkhamsing/open-source-ios-apps
    parallelism: 
    shell: /bin/bash 
    docker:
    - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
    steps:
    - checkout
    - run:
        working_directory: ~/dkhamsing/open-source-ios-apps
        command: dkhamsing/open-ios-apps/.rvmrc; echo 2.4.0 .
    - restore_cache:
        keys:
        - v1-dep-{{ .Branch }}-
        - v1-dep-master-
        - v1-dep-
    - save_cache:
        key: v1-dep

        paths:
        - vendor/bundle
        - ~/virtualenvs
        - ~/.m2
        - ~/.ivy2
        - ~/.bundle
        - ~/.go_workspace
        - ~/.gradle
        - ~/.cache/bower
    - run: github/osia_convert.rb
    - run: github/deploy.sh
    - run: gem install delete_my_tweets
    - run: ruby .github/osia_tweet_clean.rb
workflows:
  version: 
  osia:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: 
